### ISSUE TITLE
Создать Typography

### ISSUE THREAD

**Issue by rLukoyanov** [Project263/TheAestheticsMobile#20]
Создать компонент Typography. 
[Стили текста](https://m3.material.io/styles/typography/type-scale-tokens)
[Ссылка на дизай](https://www.figma.com/file/NWjPCywV5dr241QawIBQzP/the-Aesthetics-2?type=design&node-id=1-437&mode=design&t=icURwA1EbxSFFm2I-4)

Компоненты в Typography -> `Text`, `Title`

**Comment by etroynov** [comment]
done #21
