### ISSUE TITLE
Сверстать хедер приложения

### ISSUE THREAD

**Issue by rLukoyanov** [Project263/TheAestheticsMobile#4]
Сверстать хедер согласно [макету](https://www.figma.com/file/NWjPCywV5dr241QawIBQzP/the-Aesthetics-2?type=design&node-id=13-2521&mode=design&t=3vY3ZKJOwaRMAdS3-4)

![Image](https://github.com/Project263/TheAestheticsMobile/assets/105169805/688d9d3d-e72b-49c4-b3f7-e4deeb83b1b1)

При нажатии на троеточие, должно открыватся модальное окно(пустое, с кнопкой закрыть)

[Задача с модальным окном](https://github.com/Project263/TheAestheticsMobile/issues/12)

**Comment by etroynov** [comment]
done #6
